title: jjg1914.me
author: John J. Glynn IV
email: jjg1914@gmail.com
twitter_username: jjg1914
github_username:  jjg1914
markdown: kramdown
description: >
  A blog about my hobbies, usually software related.
plugins:
  - jekyll-feed
